{"name": "Невозможность изменения данных неавторизованного пользователя, name", "status": "passed", "description": "При попытке изменения возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'barkerpeter@example.org', 'password': '5697616703', 'name': 'Matthew Swanson'}"}], "start": 1718472377426, "stop": 1718472378014}, {"name": "Отправка PATCH на auth/user", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'barkerpeter@example.org', 'password': '5697616703', 'name': 'abracadabra'}"}, {"name": "access_token", "value": "''"}], "start": 1718472378014, "stop": 1718472378236}], "parameters": [{"name": "field", "value": "'name'"}], "start": 1718472377426, "stop": 1718472378237, "uuid": "507ac4cc-3330-41d7-8ab8-597a0d3808e4", "historyId": "98c1a69af1834aad658c3d0150a8bfec", "testCaseId": "ed8b5b9382a269d205c24e64879389b0", "fullName": "tests.test_auth_user.TestChangeUserData#test_change_unauthorized_user_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "24248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}