{"name": "Невозможность изменения данных неавторизованного пользователя, email", "status": "passed", "description": "При попытке изменения возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'perezkenneth@example.com', 'password': '5294285138', 'name': 'Robert Heath'}"}], "start": 1718472374137, "stop": 1718472374401}, {"name": "Отправка PATCH на auth/user", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'abracadabra', 'password': '5294285138', 'name': 'Robert Heath'}"}, {"name": "access_token", "value": "''"}], "start": 1718472374402, "stop": 1718472374639}], "parameters": [{"name": "field", "value": "'email'"}], "start": 1718472374137, "stop": 1718472374640, "uuid": "3e3ca797-4365-4c32-ae61-813aef47de03", "historyId": "7b7719bfa965413a1d89dabc1cb3e74c", "testCaseId": "ed8b5b9382a269d205c24e64879389b0", "fullName": "tests.test_auth_user.TestChangeUserData#test_change_unauthorized_user_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "24248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}