{"name": "Невозможность изменения данных неавторизованного пользователя, name", "status": "passed", "description": "При попытке изменения возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'riveradorothy@example.org', 'password': '2846450240', 'name': 'Samantha Charles'}"}], "start": 1718264935605, "stop": 1718264935937}, {"name": "Отправка PATCH на auth/user", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'riveradorothy@example.org', 'password': '2846450240', 'name': 'abracadabra'}"}, {"name": "access_token", "value": "''"}], "start": 1718264935938, "stop": 1718264936170}], "parameters": [{"name": "field", "value": "'name'"}], "start": 1718264935603, "stop": 1718264936170, "uuid": "c803509c-3a7a-4635-9274-7928db460467", "historyId": "98c1a69af1834aad658c3d0150a8bfec", "testCaseId": "ed8b5b9382a269d205c24e64879389b0", "fullName": "tests.test_auth_user.TestChangeUserData#test_change_unauthorized_user_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "30908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}