{"name": "Невозможность изменения данных неавторизованного пользователя, name", "status": "passed", "description": "При попытке изменения возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'michaelanderson@example.org', 'password': '3703766641', 'name': 'James Hess'}"}], "start": 1718266323534, "stop": 1718266323810}, {"name": "Отправка PATCH на auth/user", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'michaelanderson@example.org', 'password': '3703766641', 'name': 'abracadabra'}"}, {"name": "access_token", "value": "''"}], "start": 1718266323810, "stop": 1718266324032}], "parameters": [{"name": "field", "value": "'name'"}], "start": 1718266323533, "stop": 1718266324032, "uuid": "a6ae498d-bedc-4e4a-9515-3ba8fc729d32", "historyId": "98c1a69af1834aad658c3d0150a8bfec", "testCaseId": "ed8b5b9382a269d205c24e64879389b0", "fullName": "tests.test_auth_user.TestChangeUserData#test_change_unauthorized_user_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "28304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}