{"name": "Невозможность изменения данных неавторизованного пользователя, password", "status": "passed", "description": "При попытке изменения возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'russell53@example.com', 'password': '1105051664', 'name': 'Adrienne Garcia'}"}], "start": 1718264934177, "stop": 1718264934457}, {"name": "Отправка PATCH на auth/user", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'russell53@example.com', 'password': 'abracadabra', 'name': 'Adrienne Garcia'}"}, {"name": "access_token", "value": "''"}], "start": 1718264934458, "stop": 1718264934702}], "parameters": [{"name": "field", "value": "'password'"}], "start": 1718264934177, "stop": 1718264934702, "uuid": "2df82378-5a0d-490c-b53b-81277bc20e67", "historyId": "02d0d55364ac10aac020dd05721d7fc0", "testCaseId": "ed8b5b9382a269d205c24e64879389b0", "fullName": "tests.test_auth_user.TestChangeUserData#test_change_unauthorized_user_data_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "30908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}